# Generated by Django 3.1.2 on 2020-10-22 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_Name', models.CharField(max_length=300)),
                ('spouse_Name', models.CharField(max_length=300)),
                ('father_Name', models.CharField(max_length=300)),
                ('mother_Name', models.CharField(max_length=300)),
                ('Occupation', models.CharField(choices=[('Healthcare and medicine', 'Healthcare and medicine'), ('Arts and entertainment', 'Arts and entertainment'), ('Business', 'Business'), ('Industrial and manufacturing', 'Industrial and manufacturing'), ('Engineer', 'Engineer'), ('Law enforcement and armed forces', 'Law enforcement and armed forces'), ('Science and technology', 'Science and technology'), ('Transport', 'Transport'), ('Service(Labour)', 'Service(Labour)')], max_length=500, null=True)),
                ('Gender', models.CharField(max_length=100, null=True)),
                ('blood_Group', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('Not Known', 'Not Known')], max_length=100, null=True)),
                ('birth_date', models.DateField()),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('Darbar', models.CharField(choices=[('Shri Anand Niwas Satsang, Memnagar', 'Shri Anand Niwas Satsang, Memnagar'), ('Shri Anand Niwas Satsang, Maninagar', 'Shri Anand Niwas Satsang, Memnagar'), ('Shri Anand Niwas Satsang, SardarNagar', 'Shri Anand Niwas Satsang, Sardarnagar'), ('Shri Anand Niwas Satsang, Sahjpur', 'Shri Anand Niwas Satsang, Sahjpur')], default='Please Select Darbar', max_length=500, null=True)),
                ('Address', models.CharField(default='Please Enter Address', max_length=500)),
                ('Pincode', models.CharField(default='Please Enter Pincode', max_length=6)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('publishing_date', models.DateTimeField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
