# Generated by Django 3.1.7 on 2021-03-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0002_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
