# Generated by Django 3.1.2 on 2020-10-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0003_auto_20201023_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='uploadsto/'),
        ),
    ]
