# Generated by Django 3.1.7 on 2021-05-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0003_post_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id']},
        ),
    ]
