# Generated by Django 3.1.2 on 2020-10-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0004_auto_20201023_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
