# Generated by Django 3.1.2 on 2020-10-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0005_auto_20201025_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Darbar',
            field=models.CharField(choices=[('Shri Anand Niwas Satsang, Memnagar', 'Shri Anand Niwas Satsang, Memnagar'), ('Shri Anand Niwas Satsang, Maninagar', 'Shri Anand Niwas Satsang, Maninagar'), ('Shri Anand Niwas Satsang, SardarNagar', 'Shri Anand Niwas Satsang, Sardarnagar'), ('Shri Anand Niwas Satsang, Sahjpur', 'Shri Anand Niwas Satsang, Sahjpur')], default='Please Select Darbar', max_length=500, null=True),
        ),
    ]
