# Generated by Django 3.1.2 on 2020-11-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0007_auto_20201029_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='spouse_Name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
