# Generated by Django 3.1.2 on 2020-11-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0008_auto_20201101_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='spouse_Name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
